from setuptools import find_packages, setup

package_name = 'behavior_tree'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='cindy',
    maintainer_email='cindy.w0135@gmail.com',
    description='TODO: Package description',
    license='Apache-2.0',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'draw = behavior_tree.main:main',
            'follow = behavior_tree.main:test_follow',
            'follow-audio = behavior_tree.main:test_follow_audio',
            'follow-action = behavior_tree.main:test_follow_action',
            'test-track = behavior_tree.main:test_follow',
            'receptionist = behavior_tree.main:receptionist',
            "grasp-intel = behavior_tree.main:grasp_intel",
            'grasp-audio = behavior_tree.main:grasp_audio',
            'serve-breakfast = behavior_tree.main:serve_breakfast',
            'store-groceries = behavior_tree.main:store_groceries',
            'store-groceries-placing-only = behavior_tree.main:store_groceries_placing_only',
            'GPSR-old = behavior_tree.main:gpsr',
            'GPSR = behavior_tree.GPSR.gpsr_new:main',
            'restaurant = behavior_tree.main:restaurant',
            'help-me-carry = behavior_tree.main:help_me_carry',
            'test_follow_head = behavior_tree.Receptionist.test_follow_head:main',
            'test-prompt-reached = behavior_tree.main:test_prompt_reached',
            'inspection = behavior_tree.main:inspection',
            # GPSR orchestrator pipeline (two-layer)
            'gpsr-demo = behavior_tree.GPSR.gpsr_2ndcall:main',
            'gpsr-full = behavior_tree.GPSR.gpsr_full:main',
            'gpsr-orchestrator = behavior_tree.GPSR.gpsr_orchestrator:main',
            'gpsr-dryrun = behavior_tree.GPSR.gpsr_dryrun:main',
            'EGPSR = behavior_tree.GPSR.egpsr:main',
            # GPSR small-tree dev tests (one per atomic action)
            'gpsr-test-goto = behavior_tree.GPSR.dev_tests:main_goto',
            'gpsr-test-find-object = behavior_tree.GPSR.dev_tests:main_find_object',
            'gpsr-test-find-person = behavior_tree.GPSR.dev_tests:main_find_person',
            'gpsr-test-follow = behavior_tree.GPSR.dev_tests:main_follow',
            'gpsr-test-guide = behavior_tree.GPSR.dev_tests:main_guide',
            'gpsr-test-greet = behavior_tree.GPSR.dev_tests:main_greet',
            'gpsr-test-grasp = behavior_tree.GPSR.dev_tests:main_grasp',
            'gpsr-test-grasp-diag = behavior_tree.GPSR.dev_tests:main_grasp_diag',
            'gpsr-test-place = behavior_tree.GPSR.dev_tests:main_place',
            'gpsr-test-deliver = behavior_tree.GPSR.dev_tests:main_deliver',
            'gpsr-test-count = behavior_tree.GPSR.dev_tests:main_count',
            'gpsr-test-answer = behavior_tree.GPSR.dev_tests:main_answer_question',
            'gpsr-test-tell = behavior_tree.GPSR.dev_tests:main_tell_info',
            'gpsr-test-say = behavior_tree.GPSR.dev_tests:main_say',
            'gpsr-test-orchestrator = behavior_tree.GPSR.dev_tests:main_orchestrator',
            'gpsr-test-announce = behavior_tree.GPSR.test_uncovered_actions:main_announce',
            'gpsr-test-approach-person = behavior_tree.GPSR.test_uncovered_actions:main_approach_person',
            'gpsr-test-ask-person = behavior_tree.GPSR.test_uncovered_actions:main_ask_person',
            'gpsr-test-describe-person = behavior_tree.GPSR.test_uncovered_actions:main_describe_person',
            'gpsr-test-record-position = behavior_tree.GPSR.test_uncovered_actions:main_record_position',
            'gpsr-test-vlm = behavior_tree.GPSR.test_uncovered_actions:main_vlm_fallback',
            'gpsr-test-llm = behavior_tree.GPSR.test_uncovered_actions:main_llm_fallback',
            'gpsr-test-cmd = behavior_tree.GPSR.test_orchestrator_grammar:main',
            # two-layer planner / executor dev tests (offline)
            'gpsr-test-split = behavior_tree.GPSR.dev_tests:main_split_command',
            'gpsr-test-lower-layer = behavior_tree.GPSR.dev_tests:main_lower_layer',
            'gpsr-test-dynamic-executor = behavior_tree.GPSR.dev_tests:main_dynamic_executor',
            'gpsr-test-orchestrator-2layer = behavior_tree.GPSR.dev_tests:main_orchestrator_two_layer',
        ],
    },
)
