from glob import glob

from setuptools import find_packages, setup

package_name = "behavior_tree"

setup(
    name=package_name,
    version="0.0.0",
    packages=find_packages(),
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml"]),
        ("share/behavior_tree/launch", glob("launch/*.launch.py")),
        ("share/" + package_name + "/config", glob("config/*.json")),
    ],
    package_data={
        "behavior_tree": ["mock_config.json"],
        "behavior_tree.Receptionist": ["constants.json"],
        "behavior_tree.HRI": ["constants.json"],
        "behavior_tree.Restaurant": ["constants.json"],
        "behavior_tree.PickAndPlace": ["constants.json"],
        "behavior_tree.DoingLaundry": ["constants.json"],
    },
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="cindy",
    maintainer_email="cindy.w0135@gmail.com",
    description="TODO: Package description",
    license="Apache-2.0",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "wire_with_navigation=behavior_tree.Restaurant.wire_with_navigation:main",
            "wire_with_navigation_new=behavior_tree.Restaurant.wire_with_navigation_new:main",
            "test_matchingserver=behavior_tree.Restaurant.test_matchingserver:main",
            "test_take_order=behavior_tree.Restaurant.test_conversation:main",
            "test_restaurant_scan = behavior_tree.Restaurant.test_scan:main",
            "test_move_arm = behavior_tree.test_move_arm_teleop:main",
            "test_orientation = behavior_tree.Restaurant.test_orientation:main",
            "restaurant-demo = behavior_tree.Restaurant.restaurants_fake:main",
            "gpsr-demo = behavior_tree.GPSR.gpsr_2ndcall:main",
            "receptionist_new = behavior_tree.Receptionist.receptionist_new:main",
            "receptionist_secondcall = behavior_tree.Receptionist.receptionist_2ndcall:main",
            "draw = behavior_tree.cli_draw:main",
            "follow = behavior_tree.HelpMeCarry.cli:follow",
            "follow-audio = behavior_tree.HelpMeCarry.cli:follow_audio",
            "follow-action = behavior_tree.HelpMeCarry.cli:follow_action",
            "test-track = behavior_tree.HelpMeCarry.cli:follow",
            "receptionist = behavior_tree.Receptionist.cli:main",
            "grasp-intel = behavior_tree.grasp_intel_demo.cli:grasp_intel",
            "grasp-audio = behavior_tree.grasp_intel_demo.cli:grasp_audio",
            "serve-breakfast = behavior_tree.ServeBreakfast.cli:main",
            "store-groceries = behavior_tree.StoringGroceries.cli:main",
            "store-groceries-placing-only = behavior_tree.StoringGroceries.cli:placing_only",
            "help-me-carry = behavior_tree.HelpMeCarry.cli:help_me_carry",
            "dummy-nav = behavior_tree.dummy_nav_node:main",
            "follow-person = behavior_tree.FollowPerson.cli:main",
            "test_follow_head = behavior_tree.Receptionist.test_follow_head:main",
            "test-prompt-reached = behavior_tree.HelpMeCarry.cli:test_prompt_reached",
            "inspection = behavior_tree.Inspection.cli:main",
            "hri = behavior_tree.HRI.cli:main",
            "hri-follow = behavior_tree.HRI.follow:main",
            "hri-intake = behavior_tree.HRI.intake:main",
            "hri-intro = behavior_tree.HRI.intro:main",
            "hri-point-at-seat = behavior_tree.HRI.point_at_seat:main",
            "test-eye-contact = behavior_tree.HRI.test_eye_contact:main",
            "test-follow-head-fresh-lock = behavior_tree.HRI.test_follow_head_fresh_lock:main",
            "test-doorbell = behavior_tree.HRI.test_doorbell:main",
            "test-go-to-approach = behavior_tree.Restaurant.test_go_to_approach:main",
            "restaurant-nav-test = behavior_tree.Restaurant.restaurant_nav_test:main",
            "test-name-drink = behavior_tree.HRI.test_name_drink_extraction:main",
            # HRI finalization modules (new, 2026): real follow-host integration
            "hri-follow-real = behavior_tree.HRI.follow_real:main",
            "hri-test-handover = behavior_tree.HRI.test_bag_handover:main",
            "hri-test-arrival = behavior_tree.HRI.test_arrival:main",
            # HRI finalized 2026 production tree (real follow bag flow)
            "hri-2026 = behavior_tree.HRI.hri_2026:main",
            "pick-and-place = behavior_tree.PickAndPlace.cli:main",
            "pick-and-place-demo = behavior_tree.PickAndPlace.cli_demo:main",
            "pp-test-scan-place = behavior_tree.PickAndPlace.samplings:main_scan_place",
            "pp-test-categorize = behavior_tree.PickAndPlace.samplings:main_categorize",
            "pp-test-cleanup-loop = behavior_tree.PickAndPlace.samplings:main_cleanup_loop",
            "pp-test-breakfast = behavior_tree.PickAndPlace.samplings:main_breakfast",
            # "doing-laundry = behavior_tree.DoingLaundry.cli:main",
            "laundry-test = behavior_tree.DoingLaundry.sampling:main",
            # DoingLaundry finalization test modules (new, 2026)
            "laundry-test-fold-action = behavior_tree.DoingLaundry.test_fold_clothing_action:main",
            "laundry-test-pick = behavior_tree.DoingLaundry.test_pick_clothing:main",
            "laundry-test-locate = behavior_tree.DoingLaundry.test_locate_and_approach:main",
            # DoingLaundry finalized 2026 production tree (real FoldClothing + perception pick)
            "doing-laundry = behavior_tree.DoingLaundry.laundry:main",
            "GPSR = behavior_tree.GPSR.gpsr_new:main",
            "gpsr-full = behavior_tree.GPSR.gpsr_full:main",
            "gpsr-orchestrator = behavior_tree.GPSR.gpsr_orchestrator:main",
            "gpsr-dryrun = behavior_tree.GPSR.gpsr_dryrun:main",
            "EGPSR = behavior_tree.GPSR.egpsr:main",
            # GPSR small-tree dev tests (one per atomic action)
            "gpsr-test-goto = behavior_tree.GPSR.dev_tests:main_goto",
            "gpsr-test-find-object = behavior_tree.GPSR.dev_tests:main_find_object",
            "gpsr-test-find-person = behavior_tree.GPSR.dev_tests:main_find_person",
            "gpsr-test-follow = behavior_tree.GPSR.dev_tests:main_follow",
            "gpsr-test-guide = behavior_tree.GPSR.dev_tests:main_guide",
            "gpsr-test-greet = behavior_tree.GPSR.dev_tests:main_greet",
            "gpsr-test-grasp = behavior_tree.GPSR.dev_tests:main_grasp",
            "gpsr-test-grasp-diag = behavior_tree.GPSR.dev_tests:main_grasp_diag",
            "gpsr-test-place = behavior_tree.GPSR.dev_tests:main_place",
            "gpsr-test-deliver = behavior_tree.GPSR.dev_tests:main_deliver",
            "gpsr-test-count = behavior_tree.GPSR.dev_tests:main_count",
            "gpsr-test-answer = behavior_tree.GPSR.dev_tests:main_answer_question",
            "gpsr-test-tell = behavior_tree.GPSR.dev_tests:main_tell_info",
            "gpsr-test-say = behavior_tree.GPSR.dev_tests:main_say",
            "gpsr-test-orchestrator = behavior_tree.GPSR.dev_tests:main_orchestrator",
            # GPSR finalization tests (new, 2026): the 7 ACTION_FACTORIES not covered
            # by dev_tests + an orchestrator grammar/plan harness
            "gpsr-test-announce = behavior_tree.GPSR.test_uncovered_actions:main_announce",
            "gpsr-test-approach-person = behavior_tree.GPSR.test_uncovered_actions:main_approach_person",
            "gpsr-test-ask-person = behavior_tree.GPSR.test_uncovered_actions:main_ask_person",
            "gpsr-test-describe-person = behavior_tree.GPSR.test_uncovered_actions:main_describe_person",
            "gpsr-test-record-position = behavior_tree.GPSR.test_uncovered_actions:main_record_position",
            "gpsr-test-vlm = behavior_tree.GPSR.test_uncovered_actions:main_vlm_fallback",
            "gpsr-test-llm = behavior_tree.GPSR.test_uncovered_actions:main_llm_fallback",
            "gpsr-test-cmd = behavior_tree.GPSR.test_orchestrator_grammar:main",
            "restaurant = behavior_tree.Restaurant.cli:main",
            "restaurant-simplified = behavior_tree.Restaurant.cli:simplified",
            # Restaurant finalization tests (new, 2026): isolate the production phases
            "test-restaurant-deliver-loop = behavior_tree.Restaurant.test_deliver_loop:main",
            "test-restaurant-collect-order = behavior_tree.Restaurant.test_collect_one_order:main",
            "test-restaurant-barman = behavior_tree.Restaurant.test_barman_phase:main",
            # Restaurant order capture via free-form name+drink action (new, 2026)
            "restaurant-test-name-drink-order = behavior_tree.Restaurant.order_intake_name_drink:main",
            # Restaurant finalized 2026 production tree (captured bar pose + name+drink intake)
            "restaurant-2026 = behavior_tree.Restaurant.restaurant_v2:main",
            "grasp_once = behavior_tree.grasp_intel_demo.grasp:main",
            # Mock mode test scripts
            "test-mock-mode = behavior_tree.test_mock_mode:main",
            "test-mockable-wrapper = scripts.test_mockable_wrapper:main",
            "verify-task-endpoints = scripts.verify_task_endpoints:main",
            "load-then-match = behavior_tree.TestTrees.load_then_match:main",
            # HelpMeCarry test scripts
            "hmc-mock-nav = behavior_tree.HelpMeCarry.test.mock_nav_server:main",
            "hmc-mock-track = behavior_tree.HelpMeCarry.test.mock_track_server:main",
            "hmc-test-follow = behavior_tree.HelpMeCarry.test.test_follow:main",
            "hmc-standalone = behavior_tree.HelpMeCarry.test.standalone_test:main",
            # PickAndPlace test scripts
            "pp-nav-test = behavior_tree.PickAndPlace.dev_cli:nav_test",
            "pp-table-recognition = behavior_tree.PickAndPlace.dev_cli:table_object_recognition",
            "pp-table-grasp = behavior_tree.PickAndPlace.dev_cli:table_grasp",
            "pp-table-placing = behavior_tree.PickAndPlace.dev_cli:table_placing",
            "pp-drop-trash = behavior_tree.PickAndPlace.dev_cli:drop_trash",
            "pp-cabinet-categorization = behavior_tree.PickAndPlace.dev_cli:cabinet_categorization",
            # PickAndPlace finalization tests (new, 2026)
            "pp-test-imports = behavior_tree.PickAndPlace.test_imports_smoke:main",
            "pp-test-grasp-place-e2e = behavior_tree.PickAndPlace.test_grasp_to_place_e2e:main",
            "pp-test-cabinet-place = behavior_tree.PickAndPlace.test_cabinet_place:main",
            # PickAndPlace breakfast assembly (new, 2026): rulebook 2nd main goal
            "pp-test-breakfast-assembly = behavior_tree.PickAndPlace.breakfast_assembly:main",
            # PickAndPlace finalized 2026 production tree (routed real place + breakfast)
            "pick-and-place-2026 = behavior_tree.PickAndPlace.pick_and_place_v2:main",
        ],
    },
)
